# Generated by Django 5.1.7 on 2025-03-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'managed': False},
        ),
    ]
